import { TextElement } from "@/types/timeline";
import { TIMELINE_CONSTANTS } from "./timeline-constants";

export type SubtitleTemplate = Omit<TextElement, "id" | "startTime" | "trimStart" | "trimEnd" | "duration" | "verticalAlign"> & {
  templateId: string;
  templateName: string;
};

export const SUBTITLE_TEMPLATES: SubtitleTemplate[] = [
  {
    templateId: "classic",
    templateName: "Classic",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 48,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 400,
    rotation: 0,
    opacity: 1,
  },
  {
    templateId: "modern",
    templateName: "Modern",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 52,
    fontFamily: "Inter",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 400,
    rotation: 0,
    opacity: 1,
  },
  {
    templateId: "minimal",
    templateName: "Minimal",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 42,
    fontFamily: "Helvetica",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 380,
    rotation: 0,
    opacity: 0.9,
  },
  {
    templateId: "highContrast",
    templateName: "High Contrast",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 48,
    fontFamily: "Arial",
    color: "#ffff00",
    backgroundColor: "rgba(0, 0, 0, 0.85)",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 400,
    rotation: 0,
    opacity: 1,
  },
  {
    templateId: "news",
    templateName: "News Style",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 44,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "rgba(0, 100, 200, 0.9)",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 420,
    rotation: 0,
    opacity: 1,
  },
  {
    templateId: "karaoke",
    templateName: "Karaoke",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 56,
    fontFamily: "Impact",
    color: "#00ffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    templateId: "cinematic",
    templateName: "Cinematic",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 40,
    fontFamily: "Georgia",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "italic",
    textDecoration: "none",
    x: 0,
    y: 380,
    rotation: 0,
    opacity: 0.95,
  },
  {
    templateId: "topTitle",
    templateName: "Top Title",
    type: "text",
    name: "Subtitle",
    content: "Your subtitle here",
    fontSize: 48,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: -400,
    rotation: 0,
    opacity: 1,
  },
];

export function createSubtitleFromTemplate(
  template: SubtitleTemplate,
  startTime = 0
): Omit<TextElement, "id"> {
  const { templateId, templateName, ...elementProps } = template;
  return {
    ...elementProps,
    duration: TIMELINE_CONSTANTS.DEFAULT_TEXT_DURATION,
    startTime,
    trimStart: 0,
    trimEnd: 0,
  };
}
