import { TextElement } from "@/types/timeline";
import { TIMELINE_CONSTANTS } from "./timeline-constants";

export type TextStyleCategory =
  | "popular"
  | "subtitle"
  | "title"
  | "social"
  | "creative"
  | "minimal"
  | "emphasis";

export type TextStylePreset = Omit<
  TextElement,
  "id" | "startTime" | "trimStart" | "trimEnd" | "duration" | "verticalAlign"
> & {
  presetId: string;
  presetName: string;
  category: TextStyleCategory;
};

export const TEXT_STYLE_CATEGORIES: Record<TextStyleCategory, string> = {
  popular: "Popular",
  subtitle: "Subtitles",
  title: "Titles",
  social: "Social",
  creative: "Creative",
  minimal: "Minimal",
  emphasis: "Emphasis",
};

export const TEXT_STYLE_PRESETS: TextStylePreset[] = [
  // Popular styles
  {
    presetId: "pop-bold-white",
    presetName: "Bold White",
    category: "popular",
    type: "text",
    name: "Text",
    content: "Your text here",
    fontSize: 64,
    fontFamily: "Inter",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "pop-shadow-box",
    presetName: "Shadow Box",
    category: "popular",
    type: "text",
    name: "Text",
    content: "Your text here",
    fontSize: 56,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "rgba(0, 0, 0, 0.8)",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "pop-neon-pink",
    presetName: "Neon Pink",
    category: "popular",
    type: "text",
    name: "Text",
    content: "Your text here",
    fontSize: 60,
    fontFamily: "Impact",
    color: "#ff00ff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "pop-yellow-highlight",
    presetName: "Yellow Highlight",
    category: "popular",
    type: "text",
    name: "Text",
    content: "Your text here",
    fontSize: 52,
    fontFamily: "Arial",
    color: "#000000",
    backgroundColor: "#ffff00",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },

  // Subtitle styles (white text with black stroke)
  {
    presetId: "sub-classic",
    presetName: "Classic",
    category: "subtitle",
    type: "text",
    name: "Text",
    content: "Subtitle text",
    fontSize: 48,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 350,
    rotation: 0,
    opacity: 1,
    strokeColor: "#000000",
    strokeWidth: 4,
  },
  {
    presetId: "sub-thin-stroke",
    presetName: "Thin Stroke",
    category: "subtitle",
    type: "text",
    name: "Text",
    content: "Subtitle text",
    fontSize: 44,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 350,
    rotation: 0,
    opacity: 1,
    strokeColor: "#000000",
    strokeWidth: 2,
  },
  {
    presetId: "sub-bold-stroke",
    presetName: "Bold Stroke",
    category: "subtitle",
    type: "text",
    name: "Text",
    content: "Subtitle text",
    fontSize: 52,
    fontFamily: "Impact",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 350,
    rotation: 0,
    opacity: 1,
    strokeColor: "#000000",
    strokeWidth: 4,
  },
  {
    presetId: "sub-yellow",
    presetName: "Yellow Sub",
    category: "subtitle",
    type: "text",
    name: "Text",
    content: "Subtitle text",
    fontSize: 48,
    fontFamily: "Arial",
    color: "#ffff00",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 350,
    rotation: 0,
    opacity: 1,
    strokeColor: "#000000",
    strokeWidth: 3,
  },
  {
    presetId: "sub-cinema",
    presetName: "Cinema",
    category: "subtitle",
    type: "text",
    name: "Text",
    content: "Subtitle text",
    fontSize: 40,
    fontFamily: "Times New Roman",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "italic",
    textDecoration: "none",
    x: 0,
    y: 380,
    rotation: 0,
    opacity: 1,
    strokeColor: "#000000",
    strokeWidth: 2,
  },
  {
    presetId: "sub-modern",
    presetName: "Modern",
    category: "subtitle",
    type: "text",
    name: "Text",
    content: "Subtitle text",
    fontSize: 44,
    fontFamily: "Helvetica",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 350,
    rotation: 0,
    opacity: 1,
    strokeColor: "#222222",
    strokeWidth: 3,
  },

  // Title styles
  {
    presetId: "title-big-impact",
    presetName: "Big Impact",
    category: "title",
    type: "text",
    name: "Text",
    content: "TITLE",
    fontSize: 96,
    fontFamily: "Impact",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "title-elegant",
    presetName: "Elegant",
    category: "title",
    type: "text",
    name: "Text",
    content: "Elegant Title",
    fontSize: 72,
    fontFamily: "Georgia",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "italic",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "title-modern-serif",
    presetName: "Modern Serif",
    category: "title",
    type: "text",
    name: "Text",
    content: "Modern Title",
    fontSize: 68,
    fontFamily: "Times New Roman",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "title-underlined",
    presetName: "Underlined",
    category: "title",
    type: "text",
    name: "Text",
    content: "Title Here",
    fontSize: 64,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "underline",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },

  // Social media styles
  {
    presetId: "social-tiktok",
    presetName: "TikTok Style",
    category: "social",
    type: "text",
    name: "Text",
    content: "POV:",
    fontSize: 48,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: -300,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "social-youtube",
    presetName: "YouTube",
    category: "social",
    type: "text",
    name: "Text",
    content: "SUBSCRIBE",
    fontSize: 44,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "#ff0000",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 350,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "social-instagram",
    presetName: "Instagram",
    category: "social",
    type: "text",
    name: "Text",
    content: "@username",
    fontSize: 40,
    fontFamily: "Helvetica",
    color: "#ffffff",
    backgroundColor: "rgba(131, 58, 180, 0.9)",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 380,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "social-hashtag",
    presetName: "Hashtag",
    category: "social",
    type: "text",
    name: "Text",
    content: "#trending",
    fontSize: 44,
    fontFamily: "Arial",
    color: "#1da1f2",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },

  // Creative styles
  {
    presetId: "creative-neon-blue",
    presetName: "Neon Blue",
    category: "creative",
    type: "text",
    name: "Text",
    content: "GLOW",
    fontSize: 72,
    fontFamily: "Impact",
    color: "#00ffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "creative-neon-green",
    presetName: "Neon Green",
    category: "creative",
    type: "text",
    name: "Text",
    content: "NEON",
    fontSize: 72,
    fontFamily: "Impact",
    color: "#00ff00",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "creative-retro",
    presetName: "Retro",
    category: "creative",
    type: "text",
    name: "Text",
    content: "RETRO",
    fontSize: 64,
    fontFamily: "Courier New",
    color: "#ff6b35",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "creative-glitch",
    presetName: "Glitch",
    category: "creative",
    type: "text",
    name: "Text",
    content: "GLITCH",
    fontSize: 68,
    fontFamily: "Impact",
    color: "#ff0066",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: -2,
    opacity: 1,
  },
  {
    presetId: "creative-comic",
    presetName: "Comic",
    category: "creative",
    type: "text",
    name: "Text",
    content: "POW!",
    fontSize: 80,
    fontFamily: "Impact",
    color: "#ffcc00",
    backgroundColor: "#ff0000",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: -5,
    opacity: 1,
  },
  {
    presetId: "creative-handwritten",
    presetName: "Handwritten",
    category: "creative",
    type: "text",
    name: "Text",
    content: "hello",
    fontSize: 56,
    fontFamily: "Comic Sans MS",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 3,
    opacity: 1,
  },

  // Minimal styles
  {
    presetId: "minimal-clean",
    presetName: "Clean",
    category: "minimal",
    type: "text",
    name: "Text",
    content: "Clean Text",
    fontSize: 48,
    fontFamily: "Helvetica",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 0.9,
  },
  {
    presetId: "minimal-thin",
    presetName: "Thin",
    category: "minimal",
    type: "text",
    name: "Text",
    content: "Thin Text",
    fontSize: 52,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 0.8,
  },
  {
    presetId: "minimal-lowercase",
    presetName: "Lowercase",
    category: "minimal",
    type: "text",
    name: "Text",
    content: "minimal style",
    fontSize: 44,
    fontFamily: "Helvetica",
    color: "#cccccc",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "minimal-subtle",
    presetName: "Subtle",
    category: "minimal",
    type: "text",
    name: "Text",
    content: "subtle",
    fontSize: 40,
    fontFamily: "Georgia",
    color: "#888888",
    backgroundColor: "transparent",
    textAlign: "center",
    fontWeight: "normal",
    fontStyle: "italic",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 0.7,
  },

  // Emphasis styles
  {
    presetId: "emphasis-alert",
    presetName: "Alert",
    category: "emphasis",
    type: "text",
    name: "Text",
    content: "ALERT!",
    fontSize: 64,
    fontFamily: "Impact",
    color: "#ffffff",
    backgroundColor: "#ff0000",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "emphasis-breaking",
    presetName: "Breaking News",
    category: "emphasis",
    type: "text",
    name: "Text",
    content: "BREAKING",
    fontSize: 56,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "#cc0000",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: -380,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "emphasis-important",
    presetName: "Important",
    category: "emphasis",
    type: "text",
    name: "Text",
    content: "IMPORTANT",
    fontSize: 52,
    fontFamily: "Arial",
    color: "#000000",
    backgroundColor: "#ffd700",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: 0,
    opacity: 1,
  },
  {
    presetId: "emphasis-sale",
    presetName: "Sale",
    category: "emphasis",
    type: "text",
    name: "Text",
    content: "50% OFF",
    fontSize: 72,
    fontFamily: "Impact",
    color: "#ffffff",
    backgroundColor: "#e63946",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 0,
    y: 0,
    rotation: -10,
    opacity: 1,
  },
  {
    presetId: "emphasis-new",
    presetName: "New Badge",
    category: "emphasis",
    type: "text",
    name: "Text",
    content: "NEW",
    fontSize: 40,
    fontFamily: "Arial",
    color: "#ffffff",
    backgroundColor: "#00cc00",
    textAlign: "center",
    fontWeight: "bold",
    fontStyle: "normal",
    textDecoration: "none",
    x: 300,
    y: -300,
    rotation: 15,
    opacity: 1,
  },
];

export function createTextFromPreset(
  preset: TextStylePreset,
  startTime = 0
): Omit<TextElement, "id"> {
  const { presetId, presetName, category, ...elementProps } = preset;
  return {
    ...elementProps,
    duration: TIMELINE_CONSTANTS.DEFAULT_TEXT_DURATION,
    startTime,
    trimStart: 0,
    trimEnd: 0,
  };
}

export function getPresetsByCategory(
  category: TextStyleCategory
): TextStylePreset[] {
  return TEXT_STYLE_PRESETS.filter((preset) => preset.category === category);
}
